name: agrost_app
description: "App for farmers and plant enthusiasts"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #inner packages
  domain:
    path: ./packages/domain
  data:
    path: ./packages/data

  go_router: ^17.1.0
  equatable: ^2.0.8
  fpdart: ^1.2.0
  intl: any

  # Data management packages
  get_it: ^9.2.1
  reactive_forms: ^18.2.2
  flutter_hooks: ^0.21.3+1
  flutter_bloc: ^9.1.1
  collection: ^1.19.1
  infinite_scroll_pagination: ^5.1.1

  # UI packages
  ionicons: 0.2.2
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  google_fonts: ^8.0.2
  flex_color_scheme: ^8.4.0

  # Remote packages
  supabase_flutter: ^2.12.2

  # Local data packages
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4
  json_serializable: ^6.13.1
  build_runner: ^2.13.1
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
