// Mocks generated by Mockito 5.4.6 from annotations
// in data/test/repository_implementation/plant_repository_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:data/dto/plant_dto.dart' as _i2;
import 'package:data/dto/stage_dto.dart' as _i3;
import 'package:data/remote_data_source/plant_remote_data_source.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlantDto_0 extends _i1.SmartFake implements _i2.PlantDto {
  _FakePlantDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStageDto_1 extends _i1.SmartFake implements _i3.StageDto {
  _FakeStageDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlantRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantRemoteDataSource extends _i1.Mock
    implements _i4.PlantRemoteDataSource {
  @override
  _i5.Future<_i2.PlantDto> getPlantInfo({required int? plantId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPlantInfo, [], {#plantId: plantId}),
            returnValue: _i5.Future<_i2.PlantDto>.value(
              _FakePlantDto_0(
                this,
                Invocation.method(#getPlantInfo, [], {#plantId: plantId}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.PlantDto>.value(
              _FakePlantDto_0(
                this,
                Invocation.method(#getPlantInfo, [], {#plantId: plantId}),
              ),
            ),
          )
          as _i5.Future<_i2.PlantDto>);

  @override
  _i5.Future<_i2.PlantDto> addPlant({
    required Map<String, dynamic>? plantData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPlant, [], {#plantData: plantData}),
            returnValue: _i5.Future<_i2.PlantDto>.value(
              _FakePlantDto_0(
                this,
                Invocation.method(#addPlant, [], {#plantData: plantData}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.PlantDto>.value(
              _FakePlantDto_0(
                this,
                Invocation.method(#addPlant, [], {#plantData: plantData}),
              ),
            ),
          )
          as _i5.Future<_i2.PlantDto>);

  @override
  _i5.Future<void> updatePlant({
    required int? plantId,
    required Map<String, dynamic>? plantData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlant, [], {
              #plantId: plantId,
              #plantData: plantData,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deletePlant({required int? plantId}) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlant, [], {#plantId: plantId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.PlantDto>> getMarketPlants({
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMarketPlants, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i2.PlantDto>>.value(<_i2.PlantDto>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.PlantDto>>.value(
              <_i2.PlantDto>[],
            ),
          )
          as _i5.Future<List<_i2.PlantDto>>);

  @override
  _i5.Future<List<_i2.PlantDto>> getPlantsCreatedByUser({
    required String? userId,
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPlantsCreatedByUser, [], {
              #userId: userId,
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i2.PlantDto>>.value(<_i2.PlantDto>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.PlantDto>>.value(
              <_i2.PlantDto>[],
            ),
          )
          as _i5.Future<List<_i2.PlantDto>>);

  @override
  _i5.Future<List<_i2.PlantDto>> getUserPlants({
    required String? userId,
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPlants, [], {
              #userId: userId,
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i2.PlantDto>>.value(<_i2.PlantDto>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.PlantDto>>.value(
              <_i2.PlantDto>[],
            ),
          )
          as _i5.Future<List<_i2.PlantDto>>);

  @override
  _i5.Future<void> addStage({required Map<String, dynamic>? stageData}) =>
      (super.noSuchMethod(
            Invocation.method(#addStage, [], {#stageData: stageData}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateStage({
    required int? stageId,
    required Map<String, dynamic>? stageData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateStage, [], {
              #stageId: stageId,
              #stageData: stageData,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteStage({required int? stageId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStage, [], {#stageId: stageId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.StageDto>> getListOfStages({
    required int? plantId,
    required int? offset,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListOfStages, [], {
              #plantId: plantId,
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i3.StageDto>>.value(<_i3.StageDto>[]),
            returnValueForMissingStub: _i5.Future<List<_i3.StageDto>>.value(
              <_i3.StageDto>[],
            ),
          )
          as _i5.Future<List<_i3.StageDto>>);

  @override
  _i5.Future<_i3.StageDto> getStageInfo({required int? stageId}) =>
      (super.noSuchMethod(
            Invocation.method(#getStageInfo, [], {#stageId: stageId}),
            returnValue: _i5.Future<_i3.StageDto>.value(
              _FakeStageDto_1(
                this,
                Invocation.method(#getStageInfo, [], {#stageId: stageId}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.StageDto>.value(
              _FakeStageDto_1(
                this,
                Invocation.method(#getStageInfo, [], {#stageId: stageId}),
              ),
            ),
          )
          as _i5.Future<_i3.StageDto>);
}
